# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import captcha_pb2 as captcha__pb2


class CaptchaDecoderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Base64ToText = channel.unary_unary(
                '/swap.CaptchaDecoder/Base64ToText',
                request_serializer=captcha__pb2.Base64Input.SerializeToString,
                response_deserializer=captcha__pb2.Base64Output.FromString,
                )


class CaptchaDecoderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Base64ToText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptchaDecoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Base64ToText': grpc.unary_unary_rpc_method_handler(
                    servicer.Base64ToText,
                    request_deserializer=captcha__pb2.Base64Input.FromString,
                    response_serializer=captcha__pb2.Base64Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swap.CaptchaDecoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CaptchaDecoder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Base64ToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swap.CaptchaDecoder/Base64ToText',
            captcha__pb2.Base64Input.SerializeToString,
            captcha__pb2.Base64Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
